const mongoose = require('mongoose');

const dentistdoctorSchema = new mongoose.Schema({
  diabetesYes: String,
  diabetesNo: String,
  hypertensionYes: String,
  hypertensionNo: String,
  historyOfAsthmaYes: String,
  historyOfAsthmaNo: String,
  recentHospitalizationYes: String,
  recentHospitalizationNo: String,
  bleedingDisordersYes: String,
  bleedingDisordersNo: String,
  acidityYes: String,
  acidityNo: String,
  historyOfMyocardialInfarctionYes: String,
  historyOfMyocardialInfarctionNo: String,
  prostheticReplacementsYes: String,
  prostheticReplacementsNo: String,
  liverDiseasesYes: String,
  liverDiseasesNo: String,
  renalDiseasesYes: String,
  renalDiseasesNo: String,
  thyroidDiseasesYes: String,
  thyroidDiseasesNo: String,
  underTreatmentYes: String,
  underTreatmentNo: String,
  chiefComplaint: String,
  kindlyMentionDetails: String,
  drugsAllergy: String,
  latexAllergy: String,
  otherMaterialAllergy: String,
  pregnant: String,
  breastFeeding: String,
  hormonalTherapy: String,
  birthControlPills: String,
  tobaccoUse: String,
  tobaccoForm: String,
  tobaccoDuration: String,
  tobaccoFrequency: String,
  alcoholUse: String,
  alcoholDuration: String,
  alcoholFrequency: String,
  otherAddiction: String,
  thumbSucking: String,
  nailBiting: String,
  otherHabit: String,
  extraOralExamination: String,
  lymphNodes: String,
  tmj: String,
  intraOralExamination: String,
  teethPresent1: String,
  teethPresent2: String,
  teethPresent3: String,
  teethPresent4: String,
  occlusion: String,
  mobility: String,
  dentalCaries: String,
  pulpInfection: String,
  periodontalPockets: String,
  washingDisease: String,
  calculus: String,
  stains: String,
  introoralSoftTissues: String,
  buccalMucosa: String,
  floorOfMouth: String,
  tongue: String,
  gingiva: String,
  hardPlate: String,
  alveolarMucosa: String,
  vestibute: String,
  provisionalDiagnosis: String,
  finalDiagnosis: String,
  treatmentPlan: String,
  investigations: String,
});

const DentistDoctor = mongoose.model('DentistDoctor', dentistdoctorSchema );

module.exports = DentistDoctor;
